### ISSUE TITLE
Error when evaluating seq2seq model

### ISSUE THREAD

**Issue by nixiaoyu** [tomerwolgithub/Break#16]
When I run the example commands
```python model/run_model.py \
--input_file data/dev_dynamic.tsv \
--random_n 10 \
--model dynamic \
--model_dir trained_models/seq2seq_dynamic/ \
--evaluate
```

I got an error as follows:
```
INFO:allennlp.common.params:dataset_reader.separator_symbol = @@SEP@@
INFO:allennlp.common.params:dataset_reader.lazy = False
Traceback (most recent call last):
  File "model/run_model.py", line 147, in <module>
    main(args)
  File "model/run_model.py", line 79, in main
    extra_args=allowed_tokens)
  File "/data/home/lanyanyan/niyihan/Break/qdmr_parsing/model/seq2seq/seq2seq_model.py", line 52, in predict
    preds = self.predictor.predict_batch_json(inputs)
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 106, in predict_batch_json
    return self.predict_batch_instance(instances)
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 109, in predict_batch_instance
    outputs = self._model.forward_on_instances(instances)
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/allennlp/models/model.py", line 153, in forward_on_instances
    outputs = self.decode(self(**model_input))
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/lanyanyan/niyihan/Break/qdmr_parsing/model/seq2seq/simple_seq2seq_dynamic.py", line 239, in forward
    predictions = self._forward_beam_search(state)
  File "/data/home/lanyanyan/niyihan/Break/qdmr_parsing/model/seq2seq/simple_seq2seq_dynamic.py", line 426, in _forward_beam_search
    start_predictions, state, self.take_step)
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/allennlp/nn/beam_search.py", line 243, in search
    gather(1, expanded_backpointer).\
RuntimeError: gather_out_cpu(): Expected dtype int64 for index
INFO:allennlp.models.archival:removing temporary unarchived model dir at /tmp/tmpjy5u4qj0
```

Have you ever met this error? I am looking forward you reply and thank you very much!

**Comment by nixiaoyu** [comment]
And when running the evaluation of the copy method

```
python model/run_model.py \
--input_file data/dev.tsv \
--model copy \
--evaluate \
--num_processes 10
```

It is skipped to zero samples: 

```
skipping example: 7755
skipping example: 7756
skipping example: 7757
skipping example: 7758
skipping example: 7759
7760 of 7760                                                                            
edit op statistics: {'insertion': 0, 'deletion': 0, 'substitution': 0, 'merging': 0, 'splitting': 0}
/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "model/run_model.py", line 147, in <module>
    main(args)
  File "model/run_model.py", line 86, in main
    output_path_base=args.output_file_base, num_processes=args.num_processes)
  File "/data/home/lanyanyan/niyihan/Break/qdmr_parsing/model/model_base.py", line 130, in evaluate
    exclude_thr=5, num_processes=num_processes)
  File "/data/home/lanyanyan/niyihan/Break/qdmr_parsing/evaluation/graph_matcher.py", line 417, in get_ged_plus_scores
    np.mean(num_paths), np.min(num_paths), np.max(num_paths)))
  File "<__array_function__ internals>", line 6, in amin
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2831, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/data/home/lanyanyan/niyihan/anaconda3/envs/break/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by tomerwolgithub** [comment]
Hi @nixiaoyu , could you please provide us with the following details on your environment: OS, installed python packages, the previous commands that were executed, and whether you are running on CPU/GPU.

Also, in the first issue, are you using  your own trained dyanmic models or the pretrained model that we provide?

Last, regarding the second issue, does running the copy baseline without the `--num_processes` flag works for you?
E.g., running:
```bash
   python model/run_model.py \
   --input_file data/dev.tsv \
   --model copy \
   --evaluate \
   --random_n 10
   ```

Thanks!

**Comment by nixiaoyu** [comment]
Oh, thank you for your reply. And sorry for my late reply because I have been busy with other things recently.
I tried to run the copy baseline without the `--num_processes` as you said, but I still got the same error.
And for the seq2seq model, I use the pretrained model that you provide, and I tried both seq2seq and seq2seq_dynamic. I use anaconda3 to create a virtual environment with python 3.6.8 and intsall the packages in requirements.txt, with CUDA Version 10.2.89, torch 1.7.1, allennlp 0.8.3.

**Comment by nixiaoyu** [comment]
For the first error, I found that it is because allennlp 0.8.3 is imcompatile with torch 1.7.1, which should be changed into torch 1.1.0. 
For the second error, it is because `num_paths` in get_ged_plus_scores is empty due to skipping all the examples, leading to the zero-array error on `np.max(num_paths)` . I guess it is because the version of numpy,  maybe some versions of numpy do not report this error? Could you please tell me which version of numpy do you use? @tomerwolgithub

**Comment by tomerwolgithub** [comment]
I use `numpy 1.19.1`

**Comment by nixiaoyu** [comment]
Oh, thank you very much! Finally I found it is because  I mistakenly passed in `lexicon_file` when preprocessing data for `copy `and `copynet`, which added the `allowed_tokens` besides `source `and `target`. I set it as `None `and it works. Sorry to bother you and thank you very much!

**Comment by tomerwolgithub** [comment]
Great! Glad that it got resolved.
